version: '3'
services:
    frontend-app:
        image: node:12.16.2-alpine
        volumes:
            - ../../frontend-app:/data/app
        working_dir: /data/app
        ports:
            - "1234:1234"
            - "1235:1235" # The HMR port is buggy and it cannot be changed
        command: sh -c "npm run dev -- --port 1234 --hmr-port 1235"
